name: scan-testnet

services:
  sync-pos:
    build:
      context: .
      dockerfile: sync.Dockerfile
    env_file: .env.testnet
    command: ["sync", "pos", "-n", "test"]
    restart: unless-stopped

  sync-nft:
    build:
      context: .
      dockerfile: sync.Dockerfile
    env_file: .env.testnet
    command: ["sync", "nft", "-n", "test"]
    restart: unless-stopped

  sync-metric:
    build:
      context: .
      dockerfile: sync.Dockerfile
    env_file: .env.testnet
    command: ["sync", "metric", "-n", "test"]
    restart: unless-stopped

  sync-scriptengine:
    build:
      context: .
      dockerfile: sync.Dockerfile
    env_file: .env.testnet
    command: ["sync", "scriptengine", "-n", "test"]
    restart: unless-stopped
