version: 2.1
orbs:
  slack: circleci/slack@4.4.4
jobs:
  build_docker:
    docker:
      - image: cimg/base:2022.04
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 'docker build -t meterio/scan-api:latest -f ./api.Dockerfile .'
      - run: 'docker login -u="$DOCKERHUB_USER" -p="$DOCKERHUB_PWD" && docker push meterio/scan-api:latest'
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          custom: |
            {
              "text": "docker image meterio/scan-api:latest published !",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Docker build succeeded. :white_check_mark:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type":"mrkdwn",
                      "text": "*Image*: `$DOCKER_REPO` with tags `$DOCKER_TAGS`"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Project*: $CIRCLE_PROJECT_REPONAME on `$CIRCLE_BRANCH` branch"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit*: $CIRCLE_SHA1"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author*: $CIRCLE_USERNAME"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }

workflows:
  build_docker_flow:
    jobs:
      - build_docker:
          context:
            - dockerhub
            - slack-secrets
          filters:
            branches:
              only:
                - master
