version: 2.1
orbs:
  docker: circleci/docker@1.7.0
  slack: circleci/slack@4.4.4
jobs:
  build_docker:
    resource_class: large
    environment:
      DOCKER_REPO: meterio/scan-api
      DOCKER_TAGS: 'latest'
    executor: docker/docker
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - docker/check
      - docker/build:
          dockerfile: ./api.Dockerfile
          image: $DOCKER_REPO
          tag: $DOCKER_TAGS
      - docker/push:
          image: $DOCKER_REPO
          tag: $DOCKER_TAGS
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          custom: |
            {
              "text": "$DOCKER_REPO image with tags $DOCKER_TAGS publish succeeded!",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Docker build succeeded. :white_check_mark:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type":"mrkdwn",
                      "text": "*Image*: `$DOCKER_REPO` with tags `$DOCKER_TAGS`"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Project*: $CIRCLE_PROJECT_REPONAME on `$CIRCLE_BRANCH` branch"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit*: $CIRCLE_SHA1"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author*: $CIRCLE_USERNAME"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }

workflows:
  build_docker:
    jobs:
      - build_docker:
          context:
            - dockerhub
            - slack-secrets
          filters:
            branches:
              only:
                - master
